spring:
  application:
    name: cloud-demo-provider
    
server:
  port: 3333
  
eureka:
  client: 
    registryFetchIntervalSeconds: 10 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30